version: '3.8'

services:
  postgresdb:
    image: postgres:15-alpine
    container_name: trade-project-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trade-app-network

  app:
    build: ./trade-app
    container_name: trade-project-app
    restart: unless-stopped
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=${POSTGRESDB_DOCKER_PORT}
      - NODE_DOCKER_PORT=${NODE_DOCKER_PORT}
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - postgresdb
    networks:
      - trade-app-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  trade-app-network:
    driver: bridge